services:
  frontend:
    build: ./frontend
    environment:
      - BACKEND_BASE_URL=http://backend:8080
    depends_on:
      - backend
    expose:
      - 3000:3000
    restart: on-failure
  backend:
    build: ./backend
    expose:
      - 8080:8080
    depends_on:
      - db
    restart: on-failure
    env_file:
      - backend.env
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=5936
      - POSTGRES_DB=Diary
    volumes:
      - ./backend/initDb:/docker-entrypoint-initdb.d
      - /var/lib/postgres:/var/lib/postgresql
    expose:
      - 5432:5432
    restart: on-failure
  nginx:
    image: nginx:stable-alpine
    ports:
    - 80:80
    - 443:443
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/archive/fooddiary.xyz:/etc/nginx/ssl/fooddiary.xyz
      - ./ssl:/etc/nginx/ssl/dhparam
    restart: on-failure

