CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "RefreshToken" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Notes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AuthorId" bigint NOT NULL,
    "Text" text NOT NULL,
    "CreationTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Notes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notes_Users_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Notes_AuthorId" ON "Notes" ("AuthorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240818133355_Init', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Users" DROP COLUMN "RefreshToken";

CREATE TABLE "RefreshTokens" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "OwnerId" bigint NOT NULL,
    "SessionId" uuid NOT NULL,
    "Value" text NOT NULL,
    "Expires" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RefreshTokens_OwnerId" ON "RefreshTokens" ("OwnerId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240818153837_RefreshTokens', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Notes" ADD "CaloriesAmount" integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240820091501_UpdateNoteEntity', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "Notes" DROP COLUMN "CaloriesAmount";

ALTER TABLE "Notes" DROP COLUMN "Text";

CREATE TABLE "NoteEntryEntity" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Dish" text NOT NULL,
    "Calories" integer,
    "NoteEntityId" bigint,
    CONSTRAINT "PK_NoteEntryEntity" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NoteEntryEntity_Notes_NoteEntityId" FOREIGN KEY ("NoteEntityId") REFERENCES "Notes" ("Id")
);

CREATE INDEX "IX_NoteEntryEntity_NoteEntityId" ON "NoteEntryEntity" ("NoteEntityId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240827150234_ImproveNoteStructure', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "RefreshTokens" DROP COLUMN "SessionId";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240901080016_SimplifyRefreshToken', '8.0.8');

COMMIT;

START TRANSACTION;

ALTER TABLE "NoteEntryEntity" DROP CONSTRAINT "FK_NoteEntryEntity_Notes_NoteEntityId";

ALTER TABLE "NoteEntryEntity" DROP CONSTRAINT "PK_NoteEntryEntity";

ALTER TABLE "NoteEntryEntity" RENAME TO "NoteEntries";

ALTER INDEX "IX_NoteEntryEntity_NoteEntityId" RENAME TO "IX_NoteEntries_NoteEntityId";

ALTER TABLE "NoteEntries" ADD CONSTRAINT "PK_NoteEntries" PRIMARY KEY ("Id");

ALTER TABLE "NoteEntries" ADD CONSTRAINT "FK_NoteEntries_Notes_NoteEntityId" FOREIGN KEY ("NoteEntityId") REFERENCES "Notes" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240901080437_RenameNoteEntries', '8.0.8');

COMMIT;