import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../css/globals.css";
import { NextUIProvider } from "@nextui-org/system";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className + " min-w-full min-h-screen"}>
        <NextUIProvider>{children}</NextUIProvider>
      </body>
    </html>
  );
}
